SERVICES:
-type: web
name: vnit-admission-chatbot
runtime: python
buildCommand: pip install -r requirements.txt
startCommand: gunicorn wsgi:app --workers 1 --timeout 120 --preload
envVars:
- key: PYTHON_VERSION
value: 3.12.0
